### PR TITLE
Rename README.squirrelly to README.squirrelly.md

### PR DESCRIPTION
**Pull request by dinagraves**
This is not currently rendering but it's not an `.md` file

### CODE REVIEW

**Review by grant — CHANGES_REQUESTED** [review]
Thanks. Has this been tested with the generator? It looks like the generator expects a file without `.md`, so it may fail to `fs.readFileSync` this file if we change the file without changing the generator:

https://github.com/googleapis/google-cloudevents-python/blob/d312ca3b59a0e54193e8625345aacdef5266f5f4/gen/src/index.ts#L18

**Comment by dinagraves** [comment]
Updated the generator.

**Comment by grant** [comment]
Thanks. Has this change been tested?

**Review by grant — APPROVED** [review]

**Comment by parthea** [comment]
Hi @dinagraves @averikitsch, 
Please could you check if this is ok to merge?

**Comment by averikitsch** [comment]
@dinagraves I don't believe this needs to render as a markdown file since it is a template and will output to README.md, see https://github.com/googleapis/google-cloudevents-python/blob/0d80a6cac036a3b55b6c5f1342aeefb9c71d3dda/gen/src/index.ts#L146

**Pull request closed without merging**
